"""empty message

Revision ID: 90094edcef25
Revises: 
Create Date: 2019-12-20 21:20:27.477544

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '90094edcef25'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_index('isbn', table_name='book')
    op.drop_table('book')
    op.drop_table('rent')
    op.add_column('client', sa.Column('name', sa.String(length=255), nullable=False))
    op.add_column('client', sa.Column('password', sa.String(length=255), nullable=False))
    op.add_column('client', sa.Column('username', sa.String(length=255), nullable=False))
    op.drop_index('client_key', table_name='client')
    op.create_unique_constraint(None, 'client', ['username'])
    op.drop_column('client', 'client_key')
    op.drop_column('client', 'updated_at')
    op.drop_column('client', 'status')
    op.drop_column('client', 'deleted_at')
    op.drop_column('client', 'created_at')
    op.drop_column('client', 'client_secret')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('client_secret', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('client', sa.Column('created_at', mysql.DATETIME(), server_default=sa.text("'2019-12-17 15:40:19'"), nullable=True))
    op.add_column('client', sa.Column('deleted_at', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('client', sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.add_column('client', sa.Column('updated_at', mysql.DATETIME(), nullable=True))
    op.add_column('client', sa.Column('client_key', mysql.VARCHAR(length=30), nullable=False))
    op.drop_constraint(None, 'client', type_='unique')
    op.create_index('client_key', 'client', ['client_key'], unique=True)
    op.drop_column('client', 'username')
    op.drop_column('client', 'password')
    op.drop_column('client', 'name')
    op.create_table('rent',
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text("'2019-12-17 21:31:34'"), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('deleted_at', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('book_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('return_date', mysql.DATETIME(), server_default=sa.text("'2019-12-17 21:31:34'"), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], name='rent_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='rent_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('book',
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text("'2019-12-17 20:39:27'"), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('deleted_at', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('isbn', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('writer', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('isbn', 'book', ['isbn'], unique=True)
    op.create_table('user',
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text("'2019-12-17 19:50:13'"), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('deleted_at', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('client_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('age', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('sex', mysql.VARCHAR(length=10), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.client_id'], name='user_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
